- name: Send in-progress callback
  hosts: localhost
  gather_facts: no
  vars:
    callbackUrl: "{{ callbackUrl | default('https://default.callback.url') }}"
    token: "{{ token | default('NoToken') }}"
  tasks:
    - name: Print all variables
      debug:
        var: vars
  tasks:
    - name: Send in-progress callback
      uri:
        url: "{{ callbackUrl }}"
        method: PATCH
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Response"
                  value: "Nginx installation has failed."
                - name: "AWX Status Drop Down"
                  value: "Failed"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token }}"
      register: result

    - name: Debug callback response
      debug:
        var: result

    - name: Fail the playbook intentionally
      ansible.builtin.fail:
        msg: "Intentionally failing the playbook."
