---
- name: Simulate Nginx deployment with periodic callbacks
  hosts: localhost
  gather_facts: no
  vars:
    callbackUrl: "{{ callbackUrl | default('https://default.callback.url') }}"
    delete_inventory: "{{ delete_inventory | default('False') }}"
    dry_run: "{{ dry_run | default('False') }}"
    execution_job_tags: "{{ execution_job_tags | default('') }}"
    execution_limit: "{{ execution_limit | default('') }}"
    execution_skip_tags: "{{ execution_skip_tags | default('') }}"
    extra_vars: "{{ extra_vars | default('') }}"
    host_group: "{{ host_group | default('') }}"
    job_template_or_workflow: "{{ job_template_or_workflow | default('') }}"
    server_list: "{{ server_list | default('localhost') }}"
    server_list_separator: "{{ server_list_separator | default(',') }}"
    use_template_inventory: "{{ use_template_inventory | default('False') }}"
    cutoverTransformKey: "{{ cutoverTransformKey | default('') }}"
    token: "{{ token | default('NoToken') }}"
    callback_data: "Callback successfully executed"
    
  tasks:
    - name: Print input variables
      debug:
        msg: "callbackUrl: {{ callbackUrl }}"

    - name: Simulate Nginx installation start
      command: "sleep 5"
      async: 0
      poll: 0
      register: yum_job

    - name: Print callbackUrl
      debug:
        msg: "callbackUrl: {{ callbackUrl }}"

    - name: Send initial callback
      uri:
        url: "{{ callbackUrl }}"
        method: PATCH
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Ansible Payload"
                  value: "Nginx installation started asynchronously."
                - name: "Job Status"
                  value: "running"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token }}"

    - name: Wait for initial period
      command: "sleep 15"

    - name: Send in-progress callback
      uri:
        url: "{{ callbackUrl }}"
        method: PATCH
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Ansible Payload"
                  value: "Nginx installation in progress."
                - name: "Job Status"
                  value: "running"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token }}"

    - name: Wait for completion
      command: "sleep 15"

    - name: Simulate Nginx installation completion
      set_fact:
        nginx_result:
          changed: true
          msg: "Nginx installed successfully"
          rc: 0
          stdout: "Simulated Nginx installation output."

    - name: Prepare callback data
      set_fact:
        callback_data: "Nginx installation - executed successfully. Nginx installation result: {{ nginx_result }}"

    - name: Send completion callback
      uri:
        url: "{{ callbackUrl }}/finish"
        method: PATCH
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Ansible Payload"
                  value: "{{ callback_data }}"
                - name: "Job Status"
                  value: "successful"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ token }}"
      register: callback_response

    - name: Print callback response
      debug:
        var: callback_response
