---
- name: Simulate Nginx deployment with periodic callbacks
  hosts: localhost
  gather_facts: no
  vars:
    callbackUrl: "{{ callbackUrl | default('https://default.callback.url') }}"
    callbackToken: "{{ callbackToken | default('defaultToken') }}"

  tasks:
    - name: Simulate Nginx installation start
      command: "sleep 5"
      async: 0
      poll: 0
      register: yum_job

    - name: Send initial callback
      uri:
        url: "{{ callbackUrl }}"
        method: POST
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Response"
                  value: "Nginx installation started asynchronously."
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ callbackToken }}"

    - name: Wait for initial period
      command: "sleep 15"

    - name: Send in-progress callback
      uri:
        url: "{{ callbackUrl }}"
        method: POST
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Response"
                  value: "Nginx installation in progress."
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ callbackToken }}"

    - name: Wait for completion
      command: "sleep 15"

    - name: Simulate Nginx installation completion
      set_fact:
        nginx_result:
          changed: true
          msg: "Nginx installed successfully"
          rc: 0
          stdout: "Simulated Nginx installation output."

    - name: Prepare callback data
      set_fact:
        callback_data: "Nginx installation - executed successfully. Nginx installation result: {{ nginx_result }}"

    - name: Send completion callback
      uri:
        url: "{{ callbackUrl }}"
        method: POST
        body_format: json
        body:
          data:
            type: "task"
            attributes:
              custom_field_values:
                - name: "Response"
                  value: "{{ callback_data }}"
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer {{ callbackToken }}"
      register: callback_response

    - name: Print callback response
      debug:
        var: callback_response
